### ISSUE TITLE
Curly braces and square brackets

### ISSUE THREAD

**Issue by FemtoEmacs** [JeffBezanson/femtolisp#29]
I am currently writing a tutorial on femtolisp.  I would appreciate if the owner of this site and developer of femtolisp modify the compiler, so that curly braces be synonymous for parentheses. The rationale for the change was given in an email to Jeff. The change entails the following modification in the read.c file:

static inline int symchar(char c)
{
    static char *special = "()[]{}'\";`,\| \f\n\r\t\v";
    return !strchr(special, c);
}

/\* Recognize the tokens */
   if ((c == '(') || (c == '{')) {
        toktype = TOK_OPEN;
    }
    else if ((c == ')') || (c == '}') ) {
        toktype = TOK_CLOSE;
    }

**Comment by JeffBezanson** [comment]
Square brackets are already taken for vectors. If I add curly braces, they will have to match (i.e. `}` can only match `{` and not `(`), so that patch will not be sufficient.

Femtolisp allows { and } as identifier characters, which is arguably a bug and I think should be disabled first of all.

Then there are two further problems:

1. R6RS allows square brackets to work like parentheses, and uses only `#( )` for vectors (which femtolisp also allows). I should likely follow suit.
2. Lisps generally do not use curly braces as parentheses; they tend to be reserved for read macros and/or things like SRFI 105 (infix syntax).

So I think what we can do is (1) make {} an error, (2) make [] work like parens (with correct matching of course).

**Comment by JeffBezanson** [comment]
@FemtoEmacs I can't seem to find the email you refer to; best to post the rationale here.

**Comment by FemtoEmacs** [comment]
The email and the rationale was written by Vernon Sipple, the person who is
writing a tutorial on femtolisp. Mr. Vernon and I are using the same
machine. But I will tell him to post the rationale on the femtolisp github
site. By the way, I am very interested in the issue of bracket as well.

2016-10-19 15:17 GMT-02:00 Jeff Bezanson <notifications@github.com>:

**Comment by JeffBezanson** [comment]
Closing as dup of #30.
