### ISSUE TITLE
Inaccurate technical descriptions

### ISSUE THREAD

**Issue by FrankHB** [JeffBezanson/femtolisp#55]
The scope of "lisp" is too vague, making some statements like FUD.

> These changes have no effect except incompatibility, and often make the language worse because the new design was not as carefully thought out and has not stood the test of time.

There is indeed no effect, because "lisp" has been with incompatibility all around for decades. Which specification should count here?

> For example, how does it help to remove backquote? One design changes the syntax of quote. Some systems disallow dotted lists. (I've seen all three of these.)

Since this is the place of an implementation of "scheme-like", maybe [some official arguments](http://scheme-reports.org/2009/position-statement.html) would make the concerns more explicit. (Alternatively, see [here](http://www.bayleshanks.com/proj-plbook-plChLispLangs) and look for "The feature list in the 2009 Steering Committee Position Statement" for the summary.) In short, none of statements about the features seems consistent with the descriptions here - even Scheme does not attribute these features to being compatible. So why changes making "incompatibility" significant for a broader set of the dialects?

> What's the point? Implementers wave the banner of "simplicity", yet wedge in all kinds of weird implicit behaviors and extra evaluation rules.

I'd also argue that at least some of the changes are meaningful despite to the sense of implementations. For example, [PicoLisp changes `quote` to be the replacement of `lambda` abstraction constructor](https://software-lab.de/doc/faq.html#lambda). The change is significant but less important than the fact of missing of `lambda`. (I don't like the change. There are alternatives, e.g. they can rename `quote` to `lambda` - but it would probably lead to more serious confusion.) I find no sufficient proof to show it "make the language worse", nor "has not stood the test of time". Actually, the design shares the spirit of so-called [FEXPRs](https://en.wikipedia.org/wiki/Fexpr) in ancient lisp dialects, though FEXPRs have been extinct in most popular standardized dialects like Common Lisp and Scheme. The `quote` special form itself can also be expressed via `$vau` operator in [the Kernel programming language](https://web.cs.wpi.edu/~jshutt/kernel.html) which has a strictly simpler evaluation algorithm than Scheme's, so "extra evaluation rules" is false. (Actually, in Kernel there is no need to backquote or quote things. The simplicity in the language design make it somewhat nearer to the original purpose of the Scheme language than current RnRS Scheme dialects, even though replacing hygienic macros by `$vau` and direct `eval` style rules Kernel out of those dialects.)

**Comment by FrankHB** [comment]
> Lately a surprising amount of FUD has been spread about tail call optimization. I agree that not every language needs it, but I would like to refute the idea that it makes interpreters slow. Look at the "tiny" subdirectory or the "interpreter" branch to see a pure s-expr interpreter with efficient TCO. All you have to do is keep track of whether you're in tail position, which can be done very cheaply. These interpreters are difficult to beat for speed, yet they have lexical scope and TCO.

I suppose this paragraph are suggesting proper tail recursion instead of tail call optimization. They are certainly [different](https://groups.google.com/d/msg/comp.lang.lisp/AezzhxTliME/2Zsq7HUn_ssJ). For instance, when you're implementing a language with mandatory proper tail recursive using a hosting language with proper tail recursive support, you likely don't need TCO because native one can be sufficient. (And the point to confuse them seems exact sorts of FUD.)

**Comment by cryptorick** [comment]
"Lighten up, Francis." https://www.youtube.com/watch?v=iN-aXzpQUdw

**Comment by FrankHB** [comment]
I'm sorry but I don't have right to access youtube right now, and it maybe lasts for some days. Some texts would be appreciated:)

**Comment by JeffBezanson** [comment]
> I find no sufficient proof to show it "make the language worse"

Proof is neither possible nor required, since it's my opinion.

**Comment by FrankHB** [comment]
> Proof is neither possible nor required, since it's my opinion.

So, this part is fully subjective? Well, fair...

(Although this still counts to me as the technically inaccurate advertisement has spread, somewhat like the FUD of proper tail recursion, just not so seriously.)

**Comment by cryptorick** [comment]
> Although this still counts to me as ...

So glad you chimed in again. I was losing sleep staying up at night to find out what you were going to say.  (For days and days, I was thinking that you abandoned us!)  Really, I could not understand how Jeff could write anything with such blatant disregard of your standard of writing and your feelings about this matter. (Forget everybody else’s standards and views on the matter — you rightly surmised that yours are the most important, the supreme.)  How dare he!  But, like the hero, you came back! You came back with your snarky comments to save the day!  Certainly, you surmised well that Jeff deserved no gratitude from you because he took the time to consider your comments. Thanks yous are for losers, not heroes!  Oh yeah, he made a small change to his text, but really that’s nothing. He must continue to suffer the wrath of indignant pedants who might be slightly obtuse about literary forms of English because language barrier — er I mean heroes — when he doesn’t conform 100% to the hero’s standards and views.  Diversity is weakness!  All who disagree with us are inferior and we must continue to unproductively troll the issues of the inferior’s github repos until conformity is achieved!  Sir, you have served the Internet an outstanding brand of justice which can only be borne of great people and we salute you!
